CREATE TABLE IF NOT EXISTS account (
  id         BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id  BIGINT UNSIGNED NOT NULL COMMENT '企业id',
  balance    DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '可用余额',
  frozen     DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '冻结中',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_tenant (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='企业账户';

CREATE TABLE IF NOT EXISTS device (
  id          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id   BIGINT UNSIGNED NOT NULL COMMENT '工厂企业id',
  name        VARCHAR(64) NOT NULL COMMENT '设备名',
  model       VARCHAR(64) DEFAULT NULL COMMENT '型号',
  precision_text VARCHAR(64) DEFAULT NULL COMMENT '精度',
  parts       VARCHAR(255) DEFAULT NULL COMMENT '可加工零件',
  materials   VARCHAR(255) DEFAULT NULL COMMENT '可加工材料',
  status      VARCHAR(16) NOT NULL DEFAULT 'IDLE' COMMENT 'IDLE/IN_USE/MAINTENANCE',
  created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted     TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  KEY idx_tenant (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工厂设备';

ALTER TABLE quotation ADD COLUMN device_ids_json VARCHAR(512) NULL COMMENT '报名勾选的设备id列表JSON';
