SET @sql := (SELECT IF(COUNT(*)=0,'ALTER TABLE contract ADD COLUMN attachment_id BIGINT UNSIGNED DEFAULT NULL AFTER hash','SELECT 1') FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='contract' AND COLUMN_NAME='attachment_id');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF(COUNT(*)=0,'ALTER TABLE contract ADD COLUMN buyer_read TINYINT NOT NULL DEFAULT 0 AFTER attachment_id','SELECT 1') FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='contract' AND COLUMN_NAME='buyer_read');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF(COUNT(*)=0,'ALTER TABLE contract ADD COLUMN buyer_sign TEXT DEFAULT NULL AFTER buyer_read','SELECT 1') FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='contract' AND COLUMN_NAME='buyer_sign');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF(COUNT(*)=0,'ALTER TABLE contract ADD COLUMN factory_signs_json JSON DEFAULT NULL AFTER buyer_sign','SELECT 1') FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='contract' AND COLUMN_NAME='factory_signs_json');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF(COUNT(*)=0,'ALTER TABLE work_stage ADD COLUMN amount DECIMAL(18,2) DEFAULT NULL AFTER promised_date','SELECT 1') FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='work_stage' AND COLUMN_NAME='amount');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF(COUNT(*)=0,'ALTER TABLE work_stage ADD COLUMN escrow_status VARCHAR(16) NOT NULL DEFAULT ''NONE'' AFTER amount','SELECT 1') FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='work_stage' AND COLUMN_NAME='escrow_status');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
CREATE TABLE IF NOT EXISTS survey (
  id          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  stage_id    BIGINT UNSIGNED NOT NULL,
  order_id    BIGINT UNSIGNED NOT NULL,
  tenant_id   BIGINT UNSIGNED NOT NULL,
  role        VARCHAR(16) NOT NULL,
  scores_json JSON NOT NULL,
  created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_stage_role (stage_id, role, tenant_id),
  KEY idx_order (order_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
